---
- name: Create a sandbox instance
  hosts: localhost
  gather_facts: False
  vars:
    key_name: my-key1
    instance_type: t2.micro
    security_group: EC2SecurityGroup1
    image: ami-08962a4068733a2b6
    region: us-east-2
  tasks:
    - name: Launch instance
      ec2_instance:
         name: "build_app"
         key_name: "{{ key_name }}"
         security_group: "{{ security_group }}"
         instance_type: "{{ instance_type }}"
         image_id: "{{ image }}"
#         wait: true
         region: "{{ region }}"
#         tags:
#           name: build_app

#         instance_tags:
#           Name: build_app
         #assign_public_ip: yes
      register: ec2
    - debug:
        var: (output_text.stdout | from_json).instances

#    - name: Add new instance to host group
#      add_host:
#        hostname: "{{ item.public_ip }}"
#        groupname: launched
#      with_items: "{{ ec2.instances }}"
#
#    - name: Wait for SSH to come up
#      wait_for:
#        host: "{{ item.public_dns_name }}"
#        port: 22
#        delay: 60
#        timeout: 320
#        state: started
#      with_items: "{{ ec2.instances }}"