---
- name: Create a sandbox instance
  hosts: localhost
  gather_facts: False
  vars:
    key_name: my-key1
    instance_type: t2.micro
    security_group: EC2SecurityGroup1
    image: ami-08962a4068733a2b6
    region: us-east-2
  tasks:
    - name: Launch instance
      ec2_instance:
         name: "build_app"
         key_name: "{{ key_name }}"
         security_group: "{{ security_group }}"
         instance_type: "{{ instance_type }}"
         image_id: "{{ image }}"
         region: "{{ region }}"
         tags:
           name: build
      register: ec2
    - debug:
        var: ec2.instances

#    - name: Ensure the added instance is in /etc/ansible/hosts
#      lineinfile:
#        path: /etc/ansible/hosts
#        insertafter: '\[build\]'
#        line: "{{ item.public_ip_address }}"
#      with_items: "{{ ec2.instances }}"

    - name: Add all instance public IPs to host group
      add_host:
        hostname: "{{ item.public_ip_address }}"
        groups: build
        ansible_ssh_private_key_file: ~/.ssh/my-key.pem
      with_items: "{{ ec2.instances }}"

#- name: Create a sandbox instance
#  hosts: build
#  remote_user: ubuntu
#  vars:
#    ansible_ssh_private_key_file: "{{ key1 }}"
#  tasks:
#    - name: Echo a hello message
#      command: echo hello